#!/bin/bash
# Will be executed by ~/.xinitrc
# and will in turn execute $session_startfile

session_startfile="$HOME/.dwm/dwm-session-startuplist"
# ==============================

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi
# Load bitmap fonts:
xset +fp ~/.fonts
xset fp rehash
#sleep 1

# Load the Xresources database:
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources # Do not background!
# ---------------------------------------------------------------
# Draw the status bar:
#while true; do
#    python3 /home/laur/Documents/comp/DWM/bars/py_bar.py
#    sleep 1        # Sleep is currently provided by the py script itself
#done &
python3 $HOME/.dwm/bars/py_bar.py &

# Start the programs/scripts in $session_startfile:
if [ -f "$session_startfile" ]; then
    source $session_startfile &
else
    rxvt-unicode &
fi

sleep 3

# load keymaps: (twice; dunno why needed)
xmodmap ~/.keymaps

# loop, so exiting dwm actually restarts it without exiting clients:
#while true; do
    # Log stderror to a file
    #dwm 2>  $HOME/.logs/dwm.log
    # No error logging:
    dwm >/dev/null 2>&1
#done
